"""Add SubstituteUnavailability table

Revision ID: 8901b8e28b6f
Revises: d1a3099a805c
Create Date: 2025-07-23 16:35:28.089170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8901b8e28b6f'
down_revision = 'd1a3099a805c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['level1_admin_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('school_id')
        batch_op.drop_column('campus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('school_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
