"""Add Organization model and relationships

Revision ID: e10cae9f58b6
Revises: efbcb1203948
Create Date: 2025-07-25 10:52:34.786428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10cae9f58b6'
down_revision = 'efbcb1203948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_school_organization_id', 'organization', ['organization_id'], ['id'])
        batch_op.create_foreign_key('fk_school_level1_admin_id', 'users', ['level1_admin_id'], ['id'])

    with op.batch_alter_table('substitute_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subreq_organization_id', 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_organization_id', 'organization', ['organization_id'], ['id'])
        batch_op.create_foreign_key('fk_user_created_by', 'users', ['created_by'], ['id'])
        # Check if school_id column exists before dropping it
        try:
            batch_op.drop_column('school_id')
        except:
            pass  # Column doesn't exist, so we can ignore this

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('substitute_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
